Lag abstrakt DAO for statusrelaterte spørringer
navikt/helsearbeidsgiver-bro-sykepenger pull request #57
Opened 2024-04-04 12:05 UTC by bjerga

Denne PR-en er en forberedelse til lagring av potensielle forespørsler. Oppførselen til statusfeltet i potensielle forespørsler vil være likt dagens, så da abstraherer jeg ut den koden slik at den også kan brukes av en annen DAO.

2024-04-18 09:08 UTC, b162214 requested changes

2024-04-18 09:08 UTC, b162214 commented on src/main/kotlin/no/nav/helsearbeidsgiver/bro/sykepenger/db/Tables.kt
> +abstract class StatusTable(name: String) : Table(name) {
Er det meningen at StatusTabellen skal ha en relasjon til måde forespørsel og potensielle forespørsler?

2024-04-18 15:06 UTC, bjerga commented on src/test/resources/db/migration/V99__create_table_status.sql
> +    opprettet         TIMESTAMP   NOT NULL DEFAULT now()
Hvorfor det? Testene behøver det ikke.

2024-04-18 15:08 UTC, bjerga commented on src/main/kotlin/no/nav/helsearbeidsgiver/bro/sykepenger/db/Tables.kt
> +    abstract val status: Column<String>
Denne tabellen er abstrakt og inneholder bare et minimum av det som kreves. `ForespoerselTable`, som arver disse feltene, har en "oppdatert"-kolonne.

2024-04-18 15:09 UTC, bjerga commented on src/main/kotlin/no/nav/helsearbeidsgiver/bro/sykepenger/db/StatusDao.kt
> +    fun hentForespoerselForForespoerselId(forespoerselId: UUID): ForespoerselDto? =
Ja, enn så lenge så er de like nok til å brukes begge steder.

2024-04-18 15:11 UTC, bjerga commented on src/main/kotlin/no/nav/helsearbeidsgiver/bro/sykepenger/db/StatusDao.kt
> +            val updated =
Jeg er ikke sikker om select låser radene, men jeg mener det ikke er relevant her. Det interessante med å gjenbruke den aktive transasksjonen er oppdateringen som skjer lenger nede.

2024-04-18 15:12 UTC, bjerga commented on src/main/kotlin/no/nav/helsearbeidsgiver/bro/sykepenger/db/Tables.kt
> +abstract class StatusTable(name: String) : Table(name) {
Ja, tanken er at både "vanlige" forespørsler og potensielle forespørsler har den samme statuslogikken og derfor de samme kolonnene og DAO-funksjonene som hører til.

2024-07-31 10:33 UTC, bjerga commented
Det blir heldigvis ikke noe av potensielle forespørsler.

2024-07-31 10:33 UTC, closed without merging